[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/dashboard*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html" 
  status = 200
  conditions = {Query = {path = "!*.js,!*.css,!*.json,!*.png,!*.jpg,!*.jpeg,!*.gif,!*.ico,!*.svg,!*.xml,!*.txt,!*.html"}}
